name = "QuantLibjl_jll"
uuid = "14278492-aaf9-5525-8468-49e3f68cdca1"
version = "1.0.1+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
libcxxwrap_julia_jll = "~0.13.2"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
